services:
    predanie.bitrix24_manager:
        class: Predanie\Bitrix24Bundle\Manager\Bitrix24Manager
        arguments: ['%bitrix24_chat_id%', '%bitrix24_user_id%', '%bitrix24_webhook%']
    predanie.bitrix24_monolog_handler:
        class:  Predanie\Bitrix24Bundle\Handler\MonologHandler
        arguments: ['@request_stack', '@predanie.bitrix24_manager']