services:
    Predanie\Bitrix24Bundle\Manager\Bitrix24Manager:
        arguments:
            $chatId: '%predanie_bitrix24_monolog.chat_id%'
            $userId: '%predanie_bitrix24_monolog.user_id%'
            $webHookCode: '%predanie_bitrix24_monolog.webhook%'

    predanie.bitrix24_manager:
        class: Predanie\Bitrix24Bundle\Manager\Bitrix24Manager
        arguments: ['%predanie_bitrix24_monolog.chat_id%', '%predanie_bitrix24_monolog.user_id%', '%predanie_bitrix24_monolog.webhook%']

    predanie.bitrix24_monolog_handler:
        class:  Predanie\Bitrix24Bundle\Handler\MonologHandler
        arguments: ['@request_stack', '@predanie.bitrix24_manager']